/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*

PA2 (USART2_TX)   ----->     RX
PA3 (USART2_RX)   <-----    TX
GND               --------    GND
3.3V (optional)   ----->     VCC (only if TTL needs power)


VCC        -------->   3.3V
GND        -------->   GND
SCL        -------->   PB6  (I2C1_SCL)
SDA        -------->   PB7  (I2C1_SDA)
ADDR       -------->   GND  (Sensor address = 0x23)

*/
#include <adc.h>
#include "stm32f4xx.h"
#include "i2c.h"
#include "uart.h"
#include "bh1750.h"
#include "led.h"       // Include the new LED header
#include <stdio.h>
#include"timer.h"
#include "bme280.h"
#include "mqtt_thingspeak.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Define the Lux threshold for turning LEDs ON
#define GREENHOUSE_LUX_THRESHOLD 15000U // 15,000 lux (Vegetative growth threshold)

char msg[80];

void ESP8266_Init(void);
void ThingSpeak_MQTTSend(float, float, uint16_t, int, uint16_t);

int main(void)
{

    float temp, hum;
    uint16_t lux, gas;
    int soil;

    // Initialize UARTs
    TimerPwmInit();
    UartInit(UART_PC, BAUD_115200);   // For debugging
    UartInit(UART_ESP, BAUD_9600);  // For ESP8266
    AdcInit();
    BH1750_Init();

    ESP8266_Init();   // CONNECT WIFI + MQTT

    while (1)
    {
        // SENSOR READ
        BME280_Task(&temp, &hum);
        lux  = BH1750_ReadLux();
        soil = Moisture_Read();
        gas  = MQ135_Read();

        // CLOUD SEND
        ThingSpeak_MQTTSend(temp, hum, lux, soil, gas);

        DelayMs(20000); // ThingSpeak rate limit
    }
}


//int main(void)
//{
//    TimerPwmInit();
//    UartInit(115200);
//    I2CInit();
//    AdcInit();
//    //I2CInit1();
//    BH1750_Init();
//
//    UartPuts("Greenhouse Controller Started\r\n");
//
//    float temp, hum;
//    uint8_t soil;
//    uint16_t mq135;
//    uint16_t lux;
//    char txBuf[80];
//
//    while (1)
//    {
//        BME280_ReadTempHum(&temp, &hum);
//        soil  = MoistureReadPercent();
//        mq135 = MQ135Read();
//        lux   = BH1750_ReadLux();
//    }
//}

