/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*

PA2 (USART2_TX)   ----->     RX
PA3 (USART2_RX)   <-----    TX
GND               --------    GND
3.3V (optional)   ----->     VCC (only if TTL needs power)


VCC        -------->   3.3V
GND        -------->   GND
SCL        -------->   PB6  (I2C1_SCL)
SDA        -------->   PB7  (I2C1_SDA)
ADDR       -------->   GND  (Sensor address = 0x23)

*/
#include "stm32f4xx.h"
#include <stdio.h>

#include "uart.h"
#include "adc.h"
#include "i2c.h"
#include "i2c1.h"
#include "bh1750.h"
#include "bme280.h"
#include "timer.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Define the Lux threshold for turning LEDs ON
#define GREENHOUSE_LUX_THRESHOLD 15000U // 15,000 lux (Vegetative growth threshold)

char msg[80];

int main(void)
{
    /* ---------- BASIC INIT ---------- */
    UartInit(115200);
    UartPuts("System Booting...\r\n");

    TimerPwmInit();   // PWM for Grow Light (LED test)
    AdcInit();        // ADC for MQ135 + Soil sensor

    I2CInit();        // BH1750
    I2CInit1();       // BME280

    BH1750_Init();
    BME280_Init();

    /* ---------- MQ135 CALIBRATION ---------- */
    UartPuts("Calibrating MQ135... Keep sensor in clean air\r\n");
    MQ135_Calibrate();

    UartPuts("Greenhouse Controller Started\r\n");

    /* ---------- MAIN LOOP ---------- */
    while (1)
    {
        MoistureControl();      // Soil moisture + Pump relay
        MQ135Read();            // Air quality
        GrowLightControl();     // PWM LED brightness control
        BME280_Task();          // Temp + Humidity + Pressure

        DelayMs(2000);
    }
}
