/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*

PA2 (USART2_TX)   ----->     RX
PA3 (USART2_RX)   <-----    TX
GND               --------    GND
3.3V (optional)   ----->     VCC (only if TTL needs power)


VCC        -------->   3.3V
GND        -------->   GND
SCL        -------->   PB6  (I2C1_SCL)
SDA        -------->   PB7  (I2C1_SDA)
ADDR       -------->   GND  (Sensor address = 0x23)

*/

#include <adc.h>
#include "stm32f4xx.h"
#include "i2c.h"
#include "i2c1.h"
#include "uart.h"
#include "bh1750.h"
#include "led.h"
#include <stdio.h>
#include "timer.h"
#include "bme280.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define GREENHOUSE_LUX_THRESHOLD 15000U

char msg[80];

int main(void)
{
    UartInit(115200);
    //TimerPwmInit();
    //I2CInit();
    //AdcInit();
    I2CInit1();
    //BH1750_Init();

    UartPuts("Greenhouse Controller Started\r\n");

    while (1)
    {
       // MoistureControl();     // Soil + Pump
        //MQ135Read();           // Air quality
        //GrowLightControl();    // Grow light PWM
        BME280_Task();         // Sensor + Fan handled internally
        DelayMs(2000);
    }
}
